# Generated by Django 3.2.3 on 2021-05-18 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compra_billetes', models.DecimalField(decimal_places=4, max_digits=7)),
                ('venta_billetes', models.DecimalField(decimal_places=4, max_digits=7)),
                ('compra_divisas', models.DecimalField(decimal_places=4, max_digits=7)),
                ('venta_divisas', models.DecimalField(decimal_places=4, max_digits=7)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
